[package]
name = "multibase"
version = "0.4.0"
description = "multibase rust"
homepage = "https://github.com/multiformats/rust-multibase"
authors = ["Friedel Ziegelmayer <dignifiedquire@gmail.com>"]

keywords = ["ipld", "ipfs", "multihash", "multibase", "cid"]

license = "MIT"

readme = "README.md"

